language: php

php:
  - 7.2
  #- hhvm-3.24

services:
  - docker
  
cache:
  directories:
    - $HOME/.composer/cache
    
before_script:
  - composer install
  - php bin/console server:start
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  

script:
  - ant

after_success:
  - if [  ! $TRAVIS_PHP_VERSION=~ ^hhvm ]; then php vendor/bin/php-coveralls -v; fi
  - if [  ! $TRAVIS_PHP_VERSION=~ ^hhvm ]; then wget https://scrutinizer-ci.com/ocular.phar -t 3; fi;
  - if [  ! $TRAVIS_PHP_VERSION=~ ^hhvm ]; then php ocular.phar code-coverage:upload --format=php-clover build/artifacts/coverage/clover.xml; fi;
  - php bin/console server:stop
  #- kill `ps -ef | grep selenium | awk '{ print $2 }'`

after_failure:
  #- sudo cat $TRAVIS_BUILD_DIR/tests/var/logs/test/test.log

notifications:
  email:
  - manzolo@libero.it
