security:

    providers:
        spid_user_provider:
            id: example

    firewalls:
        spid:
            pattern: /reserved
            guard:
                provider: spid_user_provider
                authenticators:
                - spid.authenticator
