security:

    providers:
        spid_user_provider:
            id: example_user_provider

    firewalls:
        spid:
            pattern: /reserved
            guard:
                provider: spid_user_provider
                authenticators:
                - spid.authenticator
            logout_on_user_change: true
